[package]
name = "percli-program"
description = "Solana program for the Percolator risk engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "percli_program"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "1.0"
anchor-spl = { version = "1.0", features = ["token"] }
percli-core = { version = "0.7.0", path = "../percli-core", features = ["solana"] }
bytemuck = { version = "1", features = ["derive"] }
pyth-sdk-solana = "0.10"

[dev-dependencies]
percli-core = { path = "../percli-core" }
solana-program-test = "2.2"
solana-sdk = "2.2"
spl-token = "7"
spl-associated-token-account = "6"
tokio = { version = "1", features = ["full"] }
borsh = "1"
sha2 = "0.10"
