[package]
name = "percli-chain"
description = "Solana on-chain client for the Percolator risk engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
percli-core = { version = "0.4.0", path = "../percli-core" }
solana-sdk = "2.2"
solana-client = "2.2"
borsh = "1"
sha2 = "0.10"
anyhow = "1"
serde_json = "1"
