[package]
name = "percli"
description = "Offline CLI simulator for the Percolator risk engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "percli"
path = "src/main.rs"

[dependencies]
percli-core = { version = "0.8.0", path = "../percli-core" }
percli-chain = { version = "0.8", path = "../percli-chain", optional = true }
solana-sdk = { version = "2.2", optional = true }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
anyhow = "1"
comfy-table = "7"
owo-colors = { version = "4", features = ["supports-colors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"], optional = true }

[features]
default = []
chain = ["percli-chain", "solana-sdk", "tracing-subscriber"]
pyth = ["percli-core/pyth"]

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
